//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmessageinfo
    {
        public int mid { get; set; }
        public string sender { get; set; }
        public string recipient { get; set; }
        public string content { get; set; }
        public string fileurl { get; set; }
        public string cdate { get; set; }
        public string ctime { get; set; }
        public Nullable<int> ctype { get; set; }
    }
}
