//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mreadcount> mreadcount { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
        public virtual DbSet<uts> uts { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<querylog> querylog { get; set; }
        public virtual DbSet<r_sroompayinfo> r_sroompayinfo { get; set; }
        public virtual DbSet<spayinfo> spayinfo { get; set; }
        public virtual DbSet<sroominfo> sroominfo { get; set; }
        public virtual DbSet<srcontent> srcontent { get; set; }
        public virtual DbSet<r_scu> r_scu { get; set; }
        public virtual DbSet<mpayinfo> mpayinfo { get; set; }
        public virtual DbSet<cmessageinfo> cmessageinfo { get; set; }
        public virtual DbSet<dmessageinfo> dmessageinfo { get; set; }
        public virtual DbSet<omessageinfo> omessageinfo { get; set; }
        public virtual DbSet<r_mu> r_mu { get; set; }
        public virtual DbSet<wallet> wallet { get; set; }
        public virtual DbSet<masterinfo> masterinfo { get; set; }
        public virtual DbSet<mrcomments> mrcomments { get; set; }
        public virtual DbSet<mrcrinfo> mrcrinfo { get; set; }
        public virtual DbSet<mroominfo> mroominfo { get; set; }
    }
}
