//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrcomments
    {
        public int cid { get; set; }
        public Nullable<int> mrcrid { get; set; }
        public string content { get; set; }
        public string suserid { get; set; }
        public string ruserid { get; set; }
        public string mdate { get; set; }
        public string mtime { get; set; }
    }
}
