//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogquestionnaire
    {
        public int qid { get; set; }
        public string name { get; set; }
        public string birthday { get; set; }
        public string sex { get; set; }
        public string nativeplace { get; set; }
        public string nations { get; set; }
        public string level { get; set; }
        public string identitycard { get; set; }
        public string educated { get; set; }
        public string unit { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public Nullable<int> membersflag { get; set; }
        public string place { get; set; }
        public string qqid { get; set; }
        public string picurl { get; set; }
        public string userid { get; set; }
    }
}
