//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class organizeEntities : DbContext
    {
        public organizeEntities()
            : base("name=organizeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datacatalog> datacatalog { get; set; }
        public virtual DbSet<datainfo> datainfo { get; set; }
        public virtual DbSet<payinfo> payinfo { get; set; }
        public virtual DbSet<querylog> querylog { get; set; }
        public virtual DbSet<r_datacata> r_datacata { get; set; }
        public virtual DbSet<syslog> syslog { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
        public virtual DbSet<userlog> userlog { get; set; }
        public virtual DbSet<uts> uts { get; set; }
        public virtual DbSet<tv_datainfos> tv_datainfos { get; set; }
        public virtual DbSet<tv_purchased> tv_purchased { get; set; }
        public virtual DbSet<ogquestionnaire> ogquestionnaire { get; set; }
        public virtual DbSet<recordtel> recordtel { get; set; }
    }
}
