//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class payinfo
    {
        public int payid { get; set; }
        public string paytime { get; set; }
        public string paymount { get; set; }
        public string userid { get; set; }
        public Nullable<int> dataid { get; set; }
        public string paydate { get; set; }
        public string out_trade_no { get; set; }
        public string transaction_id { get; set; }
    }
}
