//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tv_datainfos
    {
        public int dataid { get; set; }
        public string title { get; set; }
        public string describe { get; set; }
        public string amount { get; set; }
        public string url { get; set; }
        public string signature { get; set; }
        public string type { get; set; }
        public string catainfo { get; set; }
        public int catalogid { get; set; }
        public string picurs { get; set; }
        public string picurd { get; set; }
        public string ddate { get; set; }
        public string dtime { get; set; }
    }
}
