//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public string userid { get; set; }
        public string username { get; set; }
        public string age { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string openid { get; set; }
        public string mail { get; set; }
    }
}
