//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroStartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public int wid { get; set; }
        public string userid { get; set; }
        public string amount { get; set; }
        public string wdate { get; set; }
        public string wtime { get; set; }
        public string adate { get; set; }
        public string atime { get; set; }
        public Nullable<int> subjects { get; set; }
    }
}
